### ISSUE TITLE
Name conflict with other binaries

### ISSUE THREAD

**Issue by pengux** [observing/thor#12]
I have a ruby gem on my machine which is also called [thor](https://github.com/erikhuda/thor), so when installing this package, there's a conflict. I tried to search for a way to install this using a different name but it doesn't seem like npm support this. Any other solutions?

**Comment by 3rd-Eden** [comment]
There's not really a way to fix this as far as I know, what you could do is just clone the repository, run npm install . and manually trigger the binary.
