### ISSUE TITLE
Thor with uWebSocket

### ISSUE THREAD

**Issue by albanm** [observing/thor#40]
See the issue on the uWebSockets project for details: https://github.com/uWebSockets/uWebSockets/issues/371

Sadly the communication is not going very smoothly and the author of uWebSockets marked the issue as invalid for now. I'm sorry folks if reading about thor compared to a grandma is a little saddening for some :)

**Comment by albanm** [comment]
From uWebSockers author:

> I did some digging and Thor is always leaving 4 bytes unsent, thus never finishing the message. I get a fragment that is 4 bytes too short, so I always have 4 bytes remaining until I should emit a message. After this I never get any more data. Also, the length of the mesage seems to be random and it contains strange data. Maybe Thor is broken, I don't know.

**Comment by d3x0r** [comment]
It's not 4 bytes short.

**Comment by albanm** [comment]
I guess you saw the last message on the linked issue !

alexhultman keeps saying that I tried to stress test uws while that was never the case : I stress-tested my whole application and never expected uws to be the bottleneck.

Anyway I just wanted to say that personally I don't care about this issue anymore, feel free to close it.

**Comment by d3x0r** [comment]
heh he locked the issue on his side. I'm not benchmarking either; merely testing connectivity.
HIs own benchmarks don't build without a speciflzed environment.  You have the power to close this :)
now I have to open a whole new issue that he doesn't accept data from other websocket providers correctly.  If he only works uws->uws that is pretty useless.
